#!/usr/bin/env bash
#should run the whoami command under the user passed as an argument
if [ $# -eq 0 ]; then
    echo "Please provide a username as an argument."
    exit 1
fi

# Get the username from the argument
username=$1

# Run the whoami command under the specified user
sudo -u "$username" whoami
