#!/usr/bin/env bash
#Install nginx on your web-01
# Update package lists
apt-get update

# Install nginx
apt-get install -y nginx

# Configure nginx to listen on port 80
sed -i 's/listen\s*80/listen 0.0.0.0:80/' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

# Create index.html file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html
