#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
# Update package lists
apt-get update

# Install nginx
apt-get install -y nginx

# Configure nginx to listen on port 80
sed -i 's/listen\s*80/listen 0.0.0.0:80/' /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure nginx to use the custom 404 page
sed -i 's/#error_page 404/error_page 404/' /etc/nginx/sites-available/default
sed -i '/error_page 404/s/^/#/' /etc/nginx/sites-available/default
echo " error_page 404 /404.html;" >> /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
```
