#!/usr/bin/env bash
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

ip_address=$1

echo "Pinging IP address: $ip_address"

for ((i=1; i<=5; i++)); do
  ping -c 1 $ip_address > /dev/null
  if [ $? -eq 0 ]; then
    echo "Ping $i successful!"
  else
    echo "Ping $i failed!"
  fi
done
