#!/usr/bin/env bash
# fix short and sweet
if ! command -v nginx &> /dev/null; then
    apt update
    apt install nginx -y
fi

systemctl stop apache2

grep -q 'listen 80' /etc/nginx/sites-available/default || sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default && systemctl reload nginx
