#!/usr/bin/env bash
#displays all active IPv4 IPs on the machine it’s executed on
ip_addresses=$(ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -oE '([0-9]*\.){3}[0-9]*')
echo "$ip_addresses"
