#!/usr/bin/env bash
#must be listening on all active IPs on port 8080
# Install Nginx
apt-get update
apt-get install -y nginx

# Stop Nginx service
service nginx stop

# Update Nginx configuration
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Start Nginx service
service nginx start
