#!/usr/bin/env bash
# fix short and sweet.
apt-get update
apt-get install -y nginx
service nginx stop
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx start
